CREATE TABLE tasks (
    task_id INT(11) AUTO_INCREMENT PRIMARY KEY,
    status ENUM('QUEUED', 'PROCESSING', 'COMPLETED') NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP,
    scheduled_run TIMESTAMP NOT NULL,
    locked BOOLEAN DEFAULT false
);

INSERT INTO tasks 
    (status, scheduled_run) 
VALUES
    ( 'QUEUED', DATE_ADD(NOW(), INTERVAL 2 MINUTE) ),
    ( 'QUEUED', DATE_ADD(NOW(), INTERVAL 5 MINUTE) ),
    ( 'QUEUED', DATE_ADD(NOW(), INTERVAL 10 MINUTE) ),
    ( 'QUEUED', DATE_ADD(NOW(), INTERVAL 15 MINUTE) ),
    ( 'QUEUED', DATE_ADD(NOW(), INTERVAL 25 MINUTE) ),
    ( 'QUEUED', DATE_ADD(NOW(), INTERVAL 30 MINUTE) ),
    ( 'QUEUED', DATE_ADD(NOW(), INTERVAL 40 MINUTE) ),
    ( 'QUEUED', DATE_ADD(NOW(), INTERVAL 50 MINUTE) ),
    ( 'COMPLETED', NOW());

COMMIT;